
name: Jellyfin FFmpeg Shared
run-name: Build Jellyfin FFmpeg Shared - ${{ github.event.head_commit.message }}

on:
   push:
   pull_request:
   workflow_dispatch:

permissions:
  contents: write

jobs:

  setup:
    runs-on: windows-2025-vs2026
    steps:
    - name: Pre-build check
      id: build_check
      shell: bash
      run: |
        echo "BEGIN Pre-build check"
        set -x -v -e
        echo "Preparing environment..."
        echo "END   Pre-build check"

  build:
    name: >-
      matid ${{ matrix.matid }}
    needs: setup
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.GithubActionsIgnoreFail }}
    strategy:
      fail-fast: false
      matrix:
        include:

        - matid: '01'
          os: windows-2025-vs2026
          platform: windows-mingw
          compilerEnv: CLANG64
          shellEnv: msys2 {0}
          GithubActionsIgnoreFail: false
          buildScript: 'msys2/build.sh'
        # ref: jellyfin-ffmpeg specific tag, branch, or (full)SHA passed to "Checkout Jellyfin FFmpeg Code"
        # (This is limited usefulness in producing old versions of jellyfin-ffmpeg.)
        # The branch, tag or SHA to checkout. When checking out the repository that
        # triggered a workflow, this defaults to the reference or SHA for that event.
        # Otherwise, uses the default branch.
        # https://github.com/actions/checkout/tree/9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    defaults:
      run:
        shell: ${{ matrix.shellEnv || 'bash' }}

    steps:

    - name: General Shell Environment Variables made using Bash
      shell: bash
      run: |
        set -x -v -e
        echo "BEGIN General Shell Environment Variables made using Bash"

        export TODAYSDATETIME=$(date -u +"%Y-%m-%d-%H-%M")
        if [ "${TODAYSDATETIME}" == "" ]; then export TODAYSDATETIME="notset" ; fi
        echo  "TODAYSDATETIME=${TODAYSDATETIME}" >> ${GITHUB_ENV}

        echo  "TODAYSDATETIME: ${TODAYSDATETIME}"

        export matid="${{ matrix.matid }}"
        if [ "${matid}" == "" ]; then export matid="notset"; fi
        echo "matid=${matid}" >> ${GITHUB_ENV}

        echo "matid: ${matid}"

        export os="${{ matrix.os }}"
        if [ "${os}" == "" ]; then export os="notset"; fi
        echo "os=${os}" >> ${GITHUB_ENV}

        echo "os: ${os}"

        export platform="${{ matrix.platform }}"
        if [ "${platform}" == "" ]; then export platform="notset"; fi
        echo "platform=${platform}" >> ${GITHUB_ENV}

        echo "platform: ${platform}"

        export compilerEnv="${{ matrix.compilerEnv }}"
        if [ "${compilerEnv}" == "" ]; then export compilerEnv="notset"; fi
        echo "compilerEnv=${compilerEnv}" >> ${GITHUB_ENV}

        echo "compilerEnv: ${compilerEnv}"

        export mingw_env="notset"
        if [ "${compilerEnv}" == "CLANG64" ]; then export mingw_env="clang-x86_64"; fi
        if [ "${compilerEnv}" == "notset" ];  then export mingw_env="notset"; fi
        echo "mingw_env=${mingw_env}" >> ${GITHUB_ENV}

        echo "mingw_env: ${mingw_env}"

        export MINGW_PACKAGE_PREFIX="notset"
        if [ "${mingw_env}" != "notset" ]; then export MINGW_PACKAGE_PREFIX="mingw-w64-${mingw_env}"; fi
        echo "MINGW_PACKAGE_PREFIX=${MINGW_PACKAGE_PREFIX}" >> ${GITHUB_ENV}

        echo "MINGW_PACKAGE_PREFIX: ${MINGW_PACKAGE_PREFIX}"

        export ref="${{ matrix.ref }}"
        if [ "${ref}" == "" ]; then export ref="notset"; fi
        echo "ref=${ref}" >> ${GITHUB_ENV}

        echo "ref: ${ref}"

        export shellEnv="${{ matrix.shellEnv }}"
        if [ "${shellEnv}" == "" ]; then export shellEnv="notset"; fi
        echo "shellEnv=${shellEnv}" >> ${GITHUB_ENV}

        echo "shellEnv: ${shellEnv}"

        export buildScript="${{ matrix.buildScript }}"
        if [ "${buildScript}" == "" ]; then export buildScript="notset"; fi
        echo "buildScript=${buildScript}" >> ${GITHUB_ENV}

        echo "buildScript: ${buildScript}"

        export ref_name="${{ github.ref_name }}"
        if [ "${ref_name}" == "" ]; then export ref_name="notset"; fi
        echo "ref_name=${ref_name}" >> ${GITHUB_ENV}
        
        echo "ref_name: ${ref_name}"

        export exportFileName="jellyfin-ffmpeg-shared-$(echo "${compilerEnv}" |sed 's/[A-Z]/\L&/g')"
        if [ "${exportFileName}" == "" ]; then export exportFileName="notset"; fi
        echo "exportFileName=${exportFileName}" >> ${GITHUB_ENV}

        echo "exportFileName: ${exportFileName}"

        echo "END   General Shell Environment Variables made using Bash"

    - name: Checkout This Code
      uses: actions/checkout@v7

    - name: Checkout Jellyfin FFmpeg Code
      uses: actions/checkout@v7
      with:
        repository: 'jellyfin/jellyfin-ffmpeg'
        # Relative path under $GITHUB_WORKSPACE to place the repository
        # Jellyfin(JLFN) FFmpeg(FFMPEG) source(SRC)
        ref: '${{ env.ref == 'notset' && '' || env.ref }}'
        path: JLFNFFMPEGSRC

    # texinfo - is for creating documentation
    # zip is for the build(or the jellyfin-ffmpeg author), and for MY zipping
    - name: Setup for MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: strict
        msystem: ${{ env.compilerEnv }}
        install: >-
          zip
          git
          curl
          wget
          ${{ env.MINGW_PACKAGE_PREFIX }}-toolchain
          quilt
          diffstat
          ${{ env.MINGW_PACKAGE_PREFIX }}-nasm
          ${{ env.MINGW_PACKAGE_PREFIX }}-texinfo

    - name: Modify buildScript
      env:
        msystem: ${{ env.compilerEnv }}
      run: |
        echo "BEGIN Modify buildScript"
        set -x -v -e
        if [ -d "JLFNFFMPEGSRC" ]
        then
          export BUILDSCRIPT="${buildScript}"
          echo  "BUILDSCRIPT: ${BUILDSCRIPT}"
          echo  "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          export GITHUB_WORKSPACE="$(cygpath ${GITHUB_WORKSPACE})"
          echo  "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          ls -alrt JLFNFFMPEGSRC
          cat ${GITHUB_WORKSPACE}/JLFNFFMPEGSRCtailbuildScript
          # number of the line that starts with PKG_NAME
          export PKG_NAME_LINE_NO=$(sed -n '/^PKG_NAME/=' ${GITHUB_WORKSPACE}/JLFNFFMPEGSRC/${BUILDSCRIPT})
          echo "PKG_NAME_LINE_NO: ${PKG_NAME_LINE_NO}"
          # the line that starts with PKG_NAME
          head ${GITHUB_WORKSPACE}/JLFNFFMPEGSRC/${BUILDSCRIPT} -n $((${PKG_NAME_LINE_NO}-1)) > ${GITHUB_WORKSPACE}/JLFNFFMPEGSRCheadbuildScript
          echo "head of the buildScript"
          cat ${GITHUB_WORKSPACE}/JLFNFFMPEGSRCheadbuildScript
          # modify in place, the args of the bash script
          sed -i 's/set -xe/set -x -v -e/g'                                              ${GITHUB_WORKSPACE}/JLFNFFMPEGSRCheadbuildScript
          # modify in place - the configure parameters of the head
          sed -i 's/--extra-version=Jellyfin/--extra-version=Jellyfin --enable-shared/g' ${GITHUB_WORKSPACE}/JLFNFFMPEGSRCheadbuildScript
          # modify in place - delete the line (UNTESTED)
          sed -i '/--disable-doc/d'                                                      ${GITHUB_WORKSPACE}/JLFNFFMPEGSRCheadbuildScript
          echo "New buildScript head after changes"
          cat ${GITHUB_WORKSPACE}/JLFNFFMPEGSRCheadbuildScript
          # rename the original
          pushd $(dirname ${GITHUB_WORKSPACE}/JLFNFFMPEGSRC/${BUILDSCRIPT})
            mv ../${BUILDSCRIPT} ../${BUILDSCRIPT}.original
          popd
          # reassemble the head and the tail
          cat ${GITHUB_WORKSPACE}/JLFNFFMPEGSRCheadbuildScript JLFNFFMPEGSRCtailbuildScript > ${GITHUB_WORKSPACE}/JLFNFFMPEGSRC/${BUILDSCRIPT}
          echo "Final new buildscript"
          cat ${GITHUB_WORKSPACE}/JLFNFFMPEGSRC/${BUILDSCRIPT}
        else
          echo A directory called \""${JLFNFFMPEGSRC}"\" was not found.  So, exiting ... ||  exit 1
        fi
        echo "END   Modify buildScript"

    - name: Run buildScript
      env:
        msystem: ${{ env.compilerEnv }}
      run: |
        echo "BEGIN Run buildScript"
        set -x -v -e
        export EXPORT_FILE_NAME="${exportFileName}"
        echo  "EXPORT_FILE_NAME: ${EXPORT_FILE_NAME}"
        export BUILDSCRIPT="${buildScript}"
        echo  "BUILDSCRIPT: ${BUILDSCRIPT}"
        echo  "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        export GITHUB_WORKSPACE="$(cygpath ${GITHUB_WORKSPACE})"
        echo  "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        # next three lines are only for testing
        mv  "${GITHUB_WORKSPACE}/JLFNFFMPEGSRC/${BUILDSCRIPT}" "${GITHUB_WORKSPACE}/JLFNFFMPEGSRC/${BUILDSCRIPT}.old"
        mv  "${GITHUB_WORKSPACE}/scriptTEST.sh"                "${GITHUB_WORKSPACE}/JLFNFFMPEGSRC/${BUILDSCRIPT}"
        # resume test or non-test
        cat "${GITHUB_WORKSPACE}/JLFNFFMPEGSRC/${BUILDSCRIPT}"
        # build the binaries
        chmod u+x "${GITHUB_WORKSPACE}/JLFNFFMPEGSRC/${BUILDSCRIPT}"
        "${GITHUB_WORKSPACE}/JLFNFFMPEGSRC/${BUILDSCRIPT}"
        echo "END   Run Modify buildScript"

    - name: For Export Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        archive: false
        path: ${{ env.EXPORT_FILE_NAME }}.zip
 
    - name: For Distribution Release
      if: >-
        ${{ github.ref_type == 'tag' }}
      uses: ncipollo/release-action@v1
      with:
        body: "## Shared Release ${{ env.PKG_VER }}  \nBuilt at the UTC date-time of ${{ env.TODAYSDATETIME }}.  "
        omitBodyDuringUpdate: true
        tag: ${{ env.ref_name }} # just look at the Artifact name to find the version. Next, push a new tag vVERSION, creating the Release
        allowUpdates: true
        replacesArtifacts: true
        artifacts: |
          ${{ env.EXPORT_FILE_NAME }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}

